import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "@/constans";


export const metadata: Metadata = {
  title: "Aira Raung",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} `}>{children}</body>
    </html>
  );
}
